### ISSUE TITLE
NextJS: use-in-view giving syntax error

### ISSUE THREAD

**Issue by albertpak** [elinadenfina/useInView#1]
Using this package in NextJS app, and running into an issue at build:
![image](https://user-images.githubusercontent.com/1485687/90470008-f4f13a00-e0df-11ea-9a09-2cc9829a4cdb.png)

```
./node_modules/use-in-view/index.js:2
import {useEffect, useState} from 'react';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at wrapSafe (internal/modules/cjs/loader.js:1070:16)
    at Module._compile (internal/modules/cjs/loader.js:1120:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Module.require (internal/modules/cjs/loader.js:1042:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at eval (webpack-internal:///use-in-view:1:18)
    at Object.use-in-view (./.next/server/pages/index.js:726:1)
    at __webpack_require__ (./.next/server/pages/index.js:23:31)
event - build page: /next/dist/pages/_error
```

here's my `.babelrc`:

```
{
  "presets": [
    "next/babel"
  ],
  "plugins": [
    "macros",
    [
      "styled-components",
      {
        "ssr": true
      }
    ]
  ]
}
```

any suggestions?

**Comment by drymek** [comment]
@albertpak have you found the solution? I'm facing the same issue.

**Comment by drymek** [comment]
```
'use strict';
const react = require('react');
const useEffect = react.useEffect;
const useState = react.useState;
const throttle = require('lodash.throttle');

module.exports = (offset = 0) => {
```
Solves the issue, but that's workaround not a solution.

**Comment by albertpak** [comment]
@drymek sorry for belated response - thank you for sharing

**Comment by bklynate** [comment]
```
const withImages = require('next-images');
const withTM = require('next-transpile-modules')(['use-in-view'])
const withPlugins = require('next-compose-plugins');
module.exports = withPlugins([withTM, withImages]);
```
This next.js configuration worked for me. I would also suggest using the same React/React-DOM that useInView is using which is  "^16.8.4" because I ran into another issue with my NextJS project using react 17

**Comment by codeashian** [comment]
Hey! Sorry, this repository is not maintained anymore. I would recommend using the `react-intersection-observer` library instead. https://www.npmjs.com/package/react-intersection-observer.
